package uz.gita.otabek.a41.presentation.home.mvp

import uz.gita.otabek.a41.R
import uz.gita.otabek.a41.data.ImageData

class HomeModel : HomeContracts.Model {
    private val images = arrayListOf(
        ImageData(
            R.drawable.iv1_q1,
            R.drawable.iv2_q1,
            R.drawable.iv3_q1,
            R.drawable.iv4_q1
        ),
        ImageData(
            R.drawable.iv1_q2,
            R.drawable.iv2_q2,
            R.drawable.iv3_q2,
            R.drawable.iv4_q2
        ),
        ImageData(
            R.drawable.iv1_q3,
            R.drawable.iv2_q3,
            R.drawable.iv3_q3,
            R.drawable.iv4_q3
        ),
        ImageData(
            R.drawable.iv1_q4,
            R.drawable.iv2_q4,
            R.drawable.iv3_q4,
            R.drawable.iv4_q4
        ),
        ImageData(
            R.drawable.iv1_q5,
            R.drawable.iv2_q5,
            R.drawable.iv3_q5,
            R.drawable.iv4_q5
        ),
        ImageData(
            R.drawable.iv1_q6,
            R.drawable.iv2_q6,
            R.drawable.iv3_q6,
            R.drawable.iv4_q6
        ),
        ImageData(
            R.drawable.iv1_q7,
            R.drawable.iv2_q7,
            R.drawable.iv3_q7,
            R.drawable.iv4_q7
        ),
        ImageData(
            R.drawable.iv1_q8,
            R.drawable.iv2_q8,
            R.drawable.iv3_q8,
            R.drawable.iv4_q8
        ),
        ImageData(
            R.drawable.iv1_q9,
            R.drawable.iv2_q9,
            R.drawable.iv3_q9,
            R.drawable.iv4_q9
        ),
        ImageData(
            R.drawable.iv1_q10,
            R.drawable.iv2_q10,
            R.drawable.iv3_q10,
            R.drawable.iv4_q10
        ),
        ImageData(
            R.drawable.iv1_q11,
            R.drawable.iv2_q11,
            R.drawable.iv3_q11,
            R.drawable.iv4_q11
        ),
        ImageData(
            R.drawable.iv1_q12,
            R.drawable.iv2_q12,
            R.drawable.iv3_q12,
            R.drawable.iv4_q12
        ),
        ImageData(
            R.drawable.iv1_q13,
            R.drawable.iv2_q13,
            R.drawable.iv3_q13,
            R.drawable.iv4_q13
        ),
        ImageData(
            R.drawable.iv1_q14,
            R.drawable.iv2_q14,
            R.drawable.iv3_q14,
            R.drawable.iv4_q14
        ),
        ImageData(
            R.drawable.iv1_q15,
            R.drawable.iv2_q15,
            R.drawable.iv3_q15,
            R.drawable.iv4_q15
        ),
        ImageData(
            R.drawable.iv1_q16,
            R.drawable.iv2_q16,
            R.drawable.iv3_q16,
            R.drawable.iv4_q16
        ),
        ImageData(
            R.drawable.iv1_q17,
            R.drawable.iv2_q17,
            R.drawable.iv3_q17,
            R.drawable.iv4_q17
        ),
        ImageData(
            R.drawable.iv1_q18,
            R.drawable.iv2_q18,
            R.drawable.iv3_q18,
            R.drawable.iv4_q18
        ),
        ImageData(
            R.drawable.iv1_q19,
            R.drawable.iv2_q19,
            R.drawable.iv3_q19,
            R.drawable.iv4_q19
        ),
        ImageData(
            R.drawable.iv1_q20,
            R.drawable.iv2_q20,
            R.drawable.iv3_q20,
            R.drawable.iv4_q20
        ),
        ImageData(
            R.drawable.iv1_q21,
            R.drawable.iv2_q21,
            R.drawable.iv3_q21,
            R.drawable.iv4_q21
        ),
        ImageData(
            R.drawable.iv1_q22,
            R.drawable.iv2_q22,
            R.drawable.iv3_q22,
            R.drawable.iv4_q22
        )
    )

    override fun getImage(index: Int): ImageData {
        return images[index]
    }
}